### USERS
###
GET http://localhost:8080/api/users

###
GET http://localhost:8080/api/users/0580d49e-db2f-4833-9ab5-e6bd682b57bb

###
GET http://localhost:8080/api/users/0580d49e-db2f-4833-9ab5-e6bd682b57b2

###
GET http://localhost:8080/api/users?loginSubstring=use&limit=2

###
DELETE http://localhost:8080/api/users/0580d49e-db2f-4833-9ab5-e6bd682b57bb

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "login": "abc",
  "password": "12",
  "age": 142
}

### GROUPS
###
GET http://localhost:8080/api/groups

###
POST http://localhost:8080/api/groups
Content-Type: application/json

{
  "name": "first",
  "permissions": ["READ", "WRITE"]
}
###
DELETE http://localhost:8080/api/groups/8031b640-e985-48a4-9bc4-7b7e6d37afaf
###
POST http://localhost:8080/api/groups/009373a8-8677-4e4a-a066-bacfd0a08eb4/users/add
Content-Type: application/json

{
  "ids": ["6668dab9-e73e-4aff-a722-2e22943798dc", "f4c31ef9-b846-48bc-b29a-7dd5770b2229"]
}
###

GET http://localhost:8080/api/groups/009373a8-8677-4e4a-a066-bacfd0a08eb4
